#pragma once


// Linked library includes
#include <SDL2/SDL.h>


static const int SCREEN_HEIGHT = 480;
static const int SCREEN_WIDTH = 640;


static const int CONTROLLER_COUNT = 4;
static const float DEFAULT_DEADZONE = 1000.0f;


static const int GCN_CONTROLLER_BUTTON_START = SDL_CONTROLLER_BUTTON_START;
static const int GCN_CONTROLLER_BUTTON_A = SDL_CONTROLLER_BUTTON_A;
static const int GCN_CONTROLLER_BUTTON_B = SDL_CONTROLLER_BUTTON_X;
static const int GCN_CONTROLLER_BUTTON_L = SDL_CONTROLLER_BUTTON_LEFTSHOULDER;
static const int GCN_CONTROLLER_BUTTON_R = SDL_CONTROLLER_BUTTON_RIGHTSHOULDER;
static const int GCN_CONTROLLER_BUTTON_X = SDL_CONTROLLER_BUTTON_B;
static const int GCN_CONTROLLER_BUTTON_Y = SDL_CONTROLLER_BUTTON_Y;
static const int GCN_CONTROLLER_BUTTON_Z = SDL_CONTROLLER_BUTTON_BACK;
static const int GCN_CONTROLLER_DPAD_UP = SDL_CONTROLLER_BUTTON_DPAD_UP;
static const int GCN_CONTROLLER_DPAD_DOWN = SDL_CONTROLLER_BUTTON_DPAD_DOWN;
static const int GCN_CONTROLLER_DPAD_LEFT = SDL_CONTROLLER_BUTTON_DPAD_LEFT;
static const int GCN_CONTROLLER_DPAD_RIGHT = SDL_CONTROLLER_BUTTON_DPAD_RIGHT;


static const float DEFAULT_GAME_OBJECT_MAX_SPEED = 1000.0f;
static constexpr const char* DEFAULT_GAME_OBJECT_NAME = "¯\\_(^_^)_/¯";


static const int PLAYER_MAXIMUM_VELOCITY = 100;
static const int PLAYER_PROJECTILE_COUNT = 50;
static const float PLAYER_PROJECTILE_VELOCITY = 350.0f;
static const float PLAYER_FIRE_RATE = 0.35f;
